
package com.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ErrorMessageException", targetNamespace = "http://cloud.mos.ru/customWebService2/")
public class ErrorMessageExceptionException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ErrorMessageException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ErrorMessageExceptionException(String message, ErrorMessageException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ErrorMessageExceptionException(String message, ErrorMessageException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.wsdl.ErrorMessageException
     */
    public ErrorMessageException getFaultInfo() {
        return faultInfo;
    }

}
