
package com.wsdl;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomWebServiceImpl", targetNamespace = "http://cloud.mos.ru/customWebService2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomWebServiceImpl {


    /**
     * 
     * @param documentId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetChildren")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "GetChildren", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDocumentRequest")
    @ResponseWrapper(localName = "DocumentIDs", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.StringArray")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetChildrenRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetChildrenResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetChildren/Fault/ErrorMessageException")
    })
    public List<String> getChildren(
        @WebParam(name = "DocumentId", targetNamespace = "")
        String documentId)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param documents
     * @param digestType
     * @return
     *     returns java.util.List<com.wsdl.DigestInfo>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetDigest")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "GetDigest", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDigestRequest")
    @ResponseWrapper(localName = "DigestInfoArray", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.DigestInfoArray")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDigestRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDigestResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDigest/Fault/ErrorMessageException")
    })
    public List<DigestInfo> getDigest(
        @WebParam(name = "Documents", targetNamespace = "")
        com.wsdl.GetDigestRequest.Documents documents,
        @WebParam(name = "DigestType", targetNamespace = "")
        String digestType)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param getFileNetId
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetFileNetId")
    @WebResult(name = "FileNetId", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "FileNetId")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetFileNetIdRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetFileNetIdResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetFileNetId/Fault/ErrorMessageException")
    })
    public String getFileNetId(
        @WebParam(name = "GetFileNetId", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "GetFileNetId")
        GetDocumentRequest getFileNetId)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param createDocument
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "CreateDocument")
    @WebResult(name = "CustomID", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "CustomID")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateDocumentRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateDocumentResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateDocument/Fault/ErrorMessageException")
    })
    public String createDocument(
        @WebParam(name = "CreateDocument", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "CreateDocument")
        CreateDocumentRequest createDocument)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param updateDocumentVersion
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "UpdateDocumentVersion")
    @WebResult(name = "UpdatedId", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "UpdatedId")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/UpdateDocumentVersionRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/UpdateDocumentVersionResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/UpdateDocumentVersion/Fault/ErrorMessageException")
    })
    public String updateDocumentVersion(
        @WebParam(name = "UpdateDocumentVersion", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "UpdateDocumentVersion")
        UpdateDocumentRequest updateDocumentVersion)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param getDocumentData
     * @return
     *     returns byte[]
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetDocumentData")
    @WebResult(name = "DocumentData", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "DocumentData")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentDataRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentDataResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentData/Fault/ErrorMessageException")
    })
    public byte[] getDocumentData(
        @WebParam(name = "GetDocumentData", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "GetDocumentData")
        GetDocumentRequest getDocumentData)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param documentId
     * @return
     *     returns com.wsdl.GetDocumentPropertiesResponse.Properties
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetDocumentProperties")
    @WebResult(name = "properties", targetNamespace = "")
    @RequestWrapper(localName = "GetDocumentProperties", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDocumentRequest")
    @ResponseWrapper(localName = "GetDocumentPropertiesResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDocumentPropertiesResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentPropertiesRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentPropertiesResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentProperties/Fault/ErrorMessageException")
    })
    public com.wsdl.GetDocumentPropertiesResponse.Properties getDocumentProperties(
        @WebParam(name = "DocumentId", targetNamespace = "")
        String documentId)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param getConvertedDocument
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetConvertedDocument")
    @WebResult(name = "DocumentID", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "DocumentID")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetConvertedDocumentRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetConvertedDocumentResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetConvertedDocument/Fault/ErrorMessageException")
    })
    public String getConvertedDocument(
        @WebParam(name = "GetConvertedDocument", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "GetConvertedDocument")
        GetDocumentRequest getConvertedDocument)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param searchQuery
     * @param storeName
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "SearchDocuments")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "SearchDocuments", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.SearchDocumentsRequest")
    @ResponseWrapper(localName = "CustomIDs", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.StringArray")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/SearchDocumentsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/SearchDocumentsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/SearchDocuments/Fault/ErrorMessageException")
    })
    public List<String> searchDocuments(
        @WebParam(name = "searchQuery", targetNamespace = "")
        String searchQuery,
        @WebParam(name = "storeName", targetNamespace = "")
        String storeName)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param deleteDocuments
     * @return
     *     returns int
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "DeleteDocuments")
    @WebResult(name = "NumOfDeleted", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "NumOfDeleted")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/DeleteDocumentsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/DeleteDocumentsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/DeleteDocuments/Fault/ErrorMessageException")
    })
    public int deleteDocuments(
        @WebParam(name = "DeleteDocuments", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "DeleteDocuments")
        DeleteDocumentsRequest deleteDocuments)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param createFolder
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "CreateFolder")
    @WebResult(name = "FolderPath", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "FolderPath")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateFolderRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateFolderResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateFolder/Fault/ErrorMessageException")
    })
    public String createFolder(
        @WebParam(name = "CreateFolder", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "CreateFolder")
        CreateFolderRequest createFolder)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param path
     * @param store
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetDocumentsInFolder")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "GetDocumentsInFolder", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetFilesInFolderRequest")
    @ResponseWrapper(localName = "DocumentsInFolder", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.StringArray")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentsInFolderRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentsInFolderResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentsInFolder/Fault/ErrorMessageException")
    })
    public List<String> getDocumentsInFolder(
        @WebParam(name = "Path", targetNamespace = "")
        String path,
        @WebParam(name = "Store", targetNamespace = "")
        String store)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param document
     * @param documentId
     * @param properties
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetDocument")
    @RequestWrapper(localName = "GetDocument", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDocumentRequest")
    @ResponseWrapper(localName = "GetDocumentResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDocumentResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocument/Fault/ErrorMessageException")
    })
    public void getDocument(
        @WebParam(name = "DocumentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "Document", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DataHandler> document,
        @WebParam(name = "properties", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<com.wsdl.GetDocumentResponse.Properties> properties)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param validateCertificate
     * @return
     *     returns com.wsdl.ValidateCertificateResponse
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "ValidateCertificate")
    @WebResult(name = "ValidateCertificateResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "ValidateCertificateResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateCertificateRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateCertificateResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateCertificate/Fault/ErrorMessageException")
    })
    public ValidateCertificateResponse validateCertificate(
        @WebParam(name = "ValidateCertificate", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "ValidateCertificate")
        byte[] validateCertificate)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param updateDocumentProperties
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "UpdateDocumentProperties")
    @WebResult(name = "UpdateDocumentPropertiesResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "UpdateDocumentPropertiesResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/UpdateDocumentPropertiesRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/UpdateDocumentPropertiesResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/UpdateDocumentProperties/Fault/ErrorMessageException")
    })
    public String updateDocumentProperties(
        @WebParam(name = "UpdateDocumentProperties", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "UpdateDocumentProperties")
        UpdatePropertiesRequest updateDocumentProperties)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param createMultipleAnnotationsRequest
     * @return
     *     returns com.wsdl.MultipleAnnotationsArray
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "CreateMultipleAnnotations")
    @WebResult(name = "MultipleAnnotationsArray", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "MultipleAnnotationsArray")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateMultipleAnnotationsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateMultipleAnnotationsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateMultipleAnnotations/Fault/ErrorMessageException")
    })
    public MultipleAnnotationsArray createMultipleAnnotations(
        @WebParam(name = "CreateMultipleAnnotationsRequest", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "CreateMultipleAnnotationsRequest")
        CreateMultipleAnnotationsRequest createMultipleAnnotationsRequest)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param annotation
     * @param documentId
     * @return
     *     returns java.util.List<com.wsdl.SignatureStatus>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "ValidateDocumentSignatures")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "ValidateDocumentSignatures", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.ValidateDocumentRequest")
    @ResponseWrapper(localName = "SignatureStatusArray", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.SignatureStatusArray")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateDocumentSignaturesRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateDocumentSignaturesResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateDocumentSignatures/Fault/ErrorMessageException")
    })
    public List<SignatureStatus> validateDocumentSignatures(
        @WebParam(name = "DocumentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "Annotation", targetNamespace = "")
        List<String> annotation)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param validateInfo
     * @param documentId
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "ValidateDocumentWithInfo")
    @RequestWrapper(localName = "ValidateDocumentWithInfo", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDocumentRequest")
    @ResponseWrapper(localName = "ValidateDocumentWithInfoResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.ValidateDocumentWithInfoResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateDocumentWithInfoRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateDocumentWithInfoResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateDocumentWithInfo/Fault/ErrorMessageException")
    })
    public void validateDocumentWithInfo(
        @WebParam(name = "DocumentId", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> documentId,
        @WebParam(name = "validateInfo", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<com.wsdl.ValidateDocumentWithInfoResponse.ValidateInfo> validateInfo)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param notAfter
     * @param advanced
     * @param failInfo
     * @param createAdvanced
     * @param documentContent
     * @param validationDate
     * @param certificateSerialNumber
     * @param signatureContent
     * @param issuer
     * @param notBefore
     * @param signer
     * @param status
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "ValidateExternalSignature")
    @RequestWrapper(localName = "ValidateExternalSignature", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.ValidateExternalSignature")
    @ResponseWrapper(localName = "ValidateExternalSignatureResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.SignatureInfoObjResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateExternalSignatureRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateExternalSignatureResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateExternalSignature/Fault/ErrorMessageException")
    })
    public void validateExternalSignature(
        @WebParam(name = "SignatureContent", targetNamespace = "")
        DataHandler signatureContent,
        @WebParam(name = "DocumentContent", targetNamespace = "")
        DataHandler documentContent,
        @WebParam(name = "CreateAdvanced", targetNamespace = "")
        boolean createAdvanced,
        @WebParam(name = "Signer", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> signer,
        @WebParam(name = "CertificateSerialNumber", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> certificateSerialNumber,
        @WebParam(name = "Issuer", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> issuer,
        @WebParam(name = "NotAfter", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Long> notAfter,
        @WebParam(name = "NotBefore", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Long> notBefore,
        @WebParam(name = "FailInfo", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> failInfo,
        @WebParam(name = "Status", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> status,
        @WebParam(name = "ValidationDate", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Long> validationDate,
        @WebParam(name = "Advanced", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DataHandler> advanced)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param property
     * @param documentId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetStringListProperty")
    @WebResult(name = "values", targetNamespace = "")
    @RequestWrapper(localName = "GetStringListProperty", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetStringListPropertyRequest")
    @ResponseWrapper(localName = "GetStringListPropertyResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetStringListPropertyResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetStringListPropertyRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetStringListPropertyResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetStringListProperty/Fault/ErrorMessageException")
    })
    public List<String> getStringListProperty(
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "property", targetNamespace = "")
        String property)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param values
     * @param property
     * @param documentId
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "AppendStringListProperty")
    @RequestWrapper(localName = "AppendStringListProperty", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.AppendStringListPropertyRequest")
    @ResponseWrapper(localName = "AppendStringListPropertyResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetStringListPropertyResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/AppendStringListPropertyRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/AppendStringListPropertyResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/AppendStringListProperty/Fault/ErrorMessageException")
    })
    public void appendStringListProperty(
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "property", targetNamespace = "")
        String property,
        @WebParam(name = "values", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<List<String>> values)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param values
     * @param property
     * @param documentId
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "RemoveFromStringListProperty")
    @RequestWrapper(localName = "RemoveFromStringListProperty", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.AppendStringListPropertyRequest")
    @ResponseWrapper(localName = "RemoveFromStringListPropertyResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetStringListPropertyResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RemoveFromStringListPropertyRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RemoveFromStringListPropertyResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RemoveFromStringListProperty/Fault/ErrorMessageException")
    })
    public void removeFromStringListProperty(
        @WebParam(name = "documentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "property", targetNamespace = "")
        String property,
        @WebParam(name = "values", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<List<String>> values)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param getCustomId
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetCustomId")
    @WebResult(name = "CustomId", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "CustomId")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetCustomIdRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetCustomIdResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetCustomId/Fault/ErrorMessageException")
    })
    public String getCustomId(
        @WebParam(name = "GetCustomId", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "GetCustomId")
        GetDocumentRequest getCustomId)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param folderDocument
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "FolderDocument")
    @WebResult(name = "FolderDocumentResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "FolderDocumentResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/FolderDocumentRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/FolderDocumentResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/FolderDocument/Fault/ErrorMessageException")
    })
    public String folderDocument(
        @WebParam(name = "FolderDocument", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "FolderDocument")
        FolderDocumentRequest folderDocument)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param path
     * @param documentClasses
     * @param store
     * @return
     *     returns java.util.List<com.wsdl.DocumentClass>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "SearchDocumentsInFolder")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "SearchDocumentsInFolder", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.SearchDocumentsInFolderRequest")
    @ResponseWrapper(localName = "DocumentClassArray", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.DocumentClassArray")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/SearchDocumentsInFolderRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/SearchDocumentsInFolderResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/SearchDocumentsInFolder/Fault/ErrorMessageException")
    })
    public List<DocumentClass> searchDocumentsInFolder(
        @WebParam(name = "Path", targetNamespace = "")
        String path,
        @WebParam(name = "Store", targetNamespace = "")
        String store,
        @WebParam(name = "DocumentClasses", targetNamespace = "")
        com.wsdl.SearchDocumentsInFolderRequest.DocumentClasses documentClasses)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param documentId
     * @param properties
     * @return
     *     returns java.util.List<com.wsdl.DocumentProperties>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetDocumentsProperties")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "GetDocumentsProperties", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDocumentsPropertiesRequest")
    @ResponseWrapper(localName = "DocumentsPropertiesResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.DocumentsPropertiesResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentsPropertiesRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentsPropertiesResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentsProperties/Fault/ErrorMessageException")
    })
    public List<DocumentProperties> getDocumentsProperties(
        @WebParam(name = "documentId", targetNamespace = "")
        List<String> documentId,
        @WebParam(name = "properties", targetNamespace = "")
        List<String> properties)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param documentId
     * @param properties
     * @return
     *     returns java.util.List<com.wsdl.DocumentStringListProperties>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetAuthProperties")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "GetAuthProperties", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDocumentsPropertiesRequest")
    @ResponseWrapper(localName = "AuthPropertiesResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.DocumentsStringListPropertiesResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetAuthPropertiesRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetAuthPropertiesResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetAuthProperties/Fault/ErrorMessageException")
    })
    public List<DocumentStringListProperties> getAuthProperties(
        @WebParam(name = "documentId", targetNamespace = "")
        List<String> documentId,
        @WebParam(name = "properties", targetNamespace = "")
        List<String> properties)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param createAnnotation
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "CreateAnnotation")
    @WebResult(name = "AnnotationId", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "AnnotationId")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateAnnotationRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateAnnotationResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateAnnotation/Fault/ErrorMessageException")
    })
    public String createAnnotation(
        @WebParam(name = "CreateAnnotation", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "CreateAnnotation")
        CreateAnnotationRequest createAnnotation)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param documentId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "RetrieveAnnotations")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "RetrieveAnnotations", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDocumentRequest")
    @ResponseWrapper(localName = "AnnotationIds", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.StringArray")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RetrieveAnnotationsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RetrieveAnnotationsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RetrieveAnnotations/Fault/ErrorMessageException")
    })
    public List<String> retrieveAnnotations(
        @WebParam(name = "DocumentId", targetNamespace = "")
        String documentId)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param deleteAnnotation
     * @return
     *     returns boolean
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "DeleteAnnotation")
    @WebResult(name = "DeleteAnnotationResult", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "DeleteAnnotationResult")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/DeleteAnnotationRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/DeleteAnnotationResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/DeleteAnnotation/Fault/ErrorMessageException")
    })
    public boolean deleteAnnotation(
        @WebParam(name = "DeleteAnnotation", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "DeleteAnnotation")
        RetrieveAnnotationRequest deleteAnnotation)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param retrieveAnnotation
     * @return
     *     returns byte[]
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "RetrieveAnnotation")
    @WebResult(name = "Annotation", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "Annotation")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RetrieveAnnotationRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RetrieveAnnotationResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RetrieveAnnotation/Fault/ErrorMessageException")
    })
    public byte[] retrieveAnnotation(
        @WebParam(name = "RetrieveAnnotation", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "RetrieveAnnotation")
        RetrieveAnnotationRequest retrieveAnnotation)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param documentId
     * @return
     *     returns java.util.List<java.lang.Boolean>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "ValidateDocument")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "ValidateDocument", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDocumentRequest")
    @ResponseWrapper(localName = "ValidateDocumentStatuses", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.BooleanArray")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateDocumentRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateDocumentResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ValidateDocument/Fault/ErrorMessageException")
    })
    public List<Boolean> validateDocument(
        @WebParam(name = "DocumentId", targetNamespace = "")
        String documentId)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param documentId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetFoldersOfDocument")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "GetFoldersOfDocument", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetFoldersOfDocumentRequest")
    @ResponseWrapper(localName = "FoldersOfDocument", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.StringArray")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetFoldersOfDocumentRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetFoldersOfDocumentResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetFoldersOfDocument/Fault/ErrorMessageException")
    })
    public List<String> getFoldersOfDocument(
        @WebParam(name = "DocumentId", targetNamespace = "")
        String documentId)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param getSignedDocumentData
     * @return
     *     returns byte[]
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetSignedDocumentData")
    @WebResult(name = "SignedDocumentData", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "SignedDocumentData")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetSignedDocumentDataRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetSignedDocumentDataResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetSignedDocumentData/Fault/ErrorMessageException")
    })
    public byte[] getSignedDocumentData(
        @WebParam(name = "GetSignedDocumentData", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "GetSignedDocumentData")
        GetDocumentRequest getSignedDocumentData)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param deleteDocumentVersion
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "DeleteDocumentVersion")
    @WebResult(name = "DeleteDocumentVersionResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "DeleteDocumentVersionResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/DeleteDocumentVersionRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/DeleteDocumentVersionResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/DeleteDocumentVersion/Fault/ErrorMessageException")
    })
    public String deleteDocumentVersion(
        @WebParam(name = "DeleteDocumentVersion", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "DeleteDocumentVersion")
        DeleteDocumentVersionRequest deleteDocumentVersion)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param documentId
     * @return
     *     returns com.wsdl.GetPermissionsResponse.Permissions
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetDocumentPermissions")
    @WebResult(name = "permissions", targetNamespace = "")
    @RequestWrapper(localName = "GetDocumentPermissions", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDocumentPermissionsRequest")
    @ResponseWrapper(localName = "PermissionsOfDocument", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetPermissionsResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentPermissionsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentPermissionsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetDocumentPermissions/Fault/ErrorMessageException")
    })
    public com.wsdl.GetPermissionsResponse.Permissions getDocumentPermissions(
        @WebParam(name = "DocumentId", targetNamespace = "")
        String documentId)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param setDocumentPermissions
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "SetDocumentPermissions")
    @WebResult(name = "SetDocumentPermissionsResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "SetDocumentPermissionsResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/SetDocumentPermissionsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/SetDocumentPermissionsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/SetDocumentPermissions/Fault/ErrorMessageException")
    })
    public String setDocumentPermissions(
        @WebParam(name = "SetDocumentPermissions", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "SetDocumentPermissions")
        SetDocumentPermissionsRequest setDocumentPermissions)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param path
     * @param store
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetFoldersInFolder")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "GetFoldersInFolder", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetFilesInFolderRequest")
    @ResponseWrapper(localName = "FoldersInFolder", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.StringArray")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetFoldersInFolderRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetFoldersInFolderResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetFoldersInFolder/Fault/ErrorMessageException")
    })
    public List<String> getFoldersInFolder(
        @WebParam(name = "Path", targetNamespace = "")
        String path,
        @WebParam(name = "Store", targetNamespace = "")
        String store)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param getParentFolder
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetParentFolder")
    @WebResult(name = "ParentFolder", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "ParentFolder")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetParentFolderRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetParentFolderResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetParentFolder/Fault/ErrorMessageException")
    })
    public String getParentFolder(
        @WebParam(name = "GetParentFolder", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "GetParentFolder")
        GetParentFolderRequest getParentFolder)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param setFolderPermissions
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "SetFolderPermissions")
    @WebResult(name = "SetFolderPermissionsResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "SetFolderPermissionsResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/SetFolderPermissionsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/SetFolderPermissionsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/SetFolderPermissions/Fault/ErrorMessageException")
    })
    public String setFolderPermissions(
        @WebParam(name = "SetFolderPermissions", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "SetFolderPermissions")
        SetFolderPermissionsRequest setFolderPermissions)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param path
     * @param store
     * @return
     *     returns com.wsdl.GetPermissionsResponse.Permissions
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetFolderPermissions")
    @WebResult(name = "permissions", targetNamespace = "")
    @RequestWrapper(localName = "GetFolderPermissions", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetFolderPermissionsRequest")
    @ResponseWrapper(localName = "PermissionsOfFolder", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetPermissionsResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetFolderPermissionsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetFolderPermissionsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetFolderPermissions/Fault/ErrorMessageException")
    })
    public com.wsdl.GetPermissionsResponse.Permissions getFolderPermissions(
        @WebParam(name = "Path", targetNamespace = "")
        String path,
        @WebParam(name = "Store", targetNamespace = "")
        String store)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param copyDocument
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "CopyDocument")
    @WebResult(name = "FileNetId", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "FileNetId")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CopyDocumentRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CopyDocumentResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CopyDocument/Fault/ErrorMessageException")
    })
    public String copyDocument(
        @WebParam(name = "CopyDocument", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "CopyDocument")
        CopyDocumentRequest copyDocument)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param moveDocument
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod
    @WebResult(name = "movedCustomId", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "movedCustomId")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/moveDocumentRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/moveDocumentResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/moveDocument/Fault/ErrorMessageException")
    })
    public String moveDocument(
        @WebParam(name = "moveDocument", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "moveDocument")
        GetDocumentRequest moveDocument)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param cancelDeferredSign
     * @return
     *     returns boolean
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "CancelDeferredSign")
    @WebResult(name = "CancelDeferredSignResult", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "CancelDeferredSignResult")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CancelDeferredSignRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CancelDeferredSignResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CancelDeferredSign/Fault/ErrorMessageException")
    })
    public boolean cancelDeferredSign(
        @WebParam(name = "CancelDeferredSign", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "CancelDeferredSign")
        CancelDeferredSignRequest cancelDeferredSign)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param objectStore
     * @param success
     * @param documentId
     * @param storageArea
     * @param failed
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "ArchiveDocuments")
    @RequestWrapper(localName = "ArchiveDocuments", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.ChangeStorageAreaRequest")
    @ResponseWrapper(localName = "ArchiveDocumentsResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.ChangeStorageAreaResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ArchiveDocumentsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ArchiveDocumentsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/ArchiveDocuments/Fault/ErrorMessageException")
    })
    public void archiveDocuments(
        @WebParam(name = "documentId", targetNamespace = "")
        List<String> documentId,
        @WebParam(name = "storageArea", targetNamespace = "")
        String storageArea,
        @WebParam(name = "objectStore", targetNamespace = "")
        String objectStore,
        @WebParam(name = "success", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<com.wsdl.ChangeStorageAreaResponse.Success> success,
        @WebParam(name = "failed", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<com.wsdl.ChangeStorageAreaResponse.Failed> failed)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param objectStore
     * @param success
     * @param documentId
     * @param storageArea
     * @param failed
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "RestoreDocuments")
    @RequestWrapper(localName = "RestoreDocuments", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.ChangeStorageAreaRequest")
    @ResponseWrapper(localName = "RestoreDocumentsResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.ChangeStorageAreaResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RestoreDocumentsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RestoreDocumentsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RestoreDocuments/Fault/ErrorMessageException")
    })
    public void restoreDocuments(
        @WebParam(name = "documentId", targetNamespace = "")
        List<String> documentId,
        @WebParam(name = "storageArea", targetNamespace = "")
        String storageArea,
        @WebParam(name = "objectStore", targetNamespace = "")
        String objectStore,
        @WebParam(name = "success", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<com.wsdl.ChangeStorageAreaResponse.Success> success,
        @WebParam(name = "failed", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<com.wsdl.ChangeStorageAreaResponse.Failed> failed)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param createDeferredAnnotationsRequest
     * @return
     *     returns java.lang.String
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "CreateDeferredAnnotations")
    @WebResult(name = "DeferredTaskId", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "DeferredTaskId")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateDeferredAnnotationsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateDeferredAnnotationsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/CreateDeferredAnnotations/Fault/ErrorMessageException")
    })
    public String createDeferredAnnotations(
        @WebParam(name = "CreateDeferredAnnotationsRequest", targetNamespace = "http://cloud.mos.ru/customWebService2/", partName = "CreateDeferredAnnotationsRequest")
        CreateDefferedAnnotationsRequest createDeferredAnnotationsRequest)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param document
     * @param annotations
     * @param documentId
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "RetrieveDocAndAnnotations")
    @RequestWrapper(localName = "RetrieveDocAndAnnotations", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetDocumentRequest")
    @ResponseWrapper(localName = "RetrieveDocAndAnnotationsResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.RetrieveDocAndAnnotationsResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RetrieveDocAndAnnotationsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RetrieveDocAndAnnotationsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RetrieveDocAndAnnotations/Fault/ErrorMessageException")
    })
    public void retrieveDocAndAnnotations(
        @WebParam(name = "DocumentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "Document", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DataHandler> document,
        @WebParam(name = "annotations", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<com.wsdl.RetrieveDocAndAnnotationsResponse.Annotations> annotations)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param document
     * @param annotations
     * @param documentId
     * @param properties
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "RetrieveDocumentAndSignatures")
    @RequestWrapper(localName = "RetrieveDocumentAndSignatures", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetAnnotationsRequest")
    @ResponseWrapper(localName = "RetrieveDocumentAndSignaturesResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.RetrieveDocAndAnnotationsResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RetrieveDocumentAndSignaturesRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RetrieveDocumentAndSignaturesResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/RetrieveDocumentAndSignatures/Fault/ErrorMessageException")
    })
    public void retrieveDocumentAndSignatures(
        @WebParam(name = "DocumentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "Properties", targetNamespace = "")
        com.wsdl.GetAnnotationsRequest.Properties properties,
        @WebParam(name = "Document", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DataHandler> document,
        @WebParam(name = "annotations", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<com.wsdl.RetrieveDocAndAnnotationsResponse.Annotations> annotations)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param searchChildren
     * @param storage
     * @param documentClass
     * @param properties
     * @return
     *     returns java.util.List<com.wsdl.DocumentProperties>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "FindDocuments")
    @WebResult(name = "item", targetNamespace = "")
    @RequestWrapper(localName = "FindDocuments", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.FindDocumentsRequest")
    @ResponseWrapper(localName = "FoundedDocuments", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.DocumentsPropertiesResponse")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/FindDocumentsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/FindDocumentsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/FindDocuments/Fault/ErrorMessageException")
    })
    public List<DocumentProperties> findDocuments(
        @WebParam(name = "documentClass", targetNamespace = "")
        String documentClass,
        @WebParam(name = "searchChildren", targetNamespace = "")
        Boolean searchChildren,
        @WebParam(name = "properties", targetNamespace = "")
        com.wsdl.FindDocumentsRequest.Properties properties,
        @WebParam(name = "storage", targetNamespace = "")
        String storage)
        throws ErrorMessageExceptionException
    ;

    /**
     * 
     * @param documentId
     * @param properties
     * @return
     *     returns java.util.List<com.wsdl.Annotation>
     * @throws ErrorMessageExceptionException
     */
    @WebMethod(operationName = "GetAnnotations")
    @WebResult(name = "Annotation", targetNamespace = "")
    @RequestWrapper(localName = "GetAnnotations", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.GetAnnotationsRequest")
    @ResponseWrapper(localName = "GetAnnotationsResponse", targetNamespace = "http://cloud.mos.ru/customWebService2/", className = "com.wsdl.Annotations")
    @Action(input = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetAnnotationsRequest", output = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetAnnotationsResponse", fault = {
        @FaultAction(className = ErrorMessageExceptionException.class, value = "http://cloud.mos.ru/customWebService2/CustomWebServiceImpl/GetAnnotations/Fault/ErrorMessageException")
    })
    public List<Annotation> getAnnotations(
        @WebParam(name = "DocumentId", targetNamespace = "")
        String documentId,
        @WebParam(name = "Properties", targetNamespace = "")
        com.wsdl.GetAnnotationsRequest.Properties properties)
        throws ErrorMessageExceptionException
    ;

}
