
package com.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomWebService", targetNamespace = "http://cloud.mos.ru/customWebService2/", wsdlLocation = "file:/C:/Users/zagvo/IdeaProjects/SOAPCall/src/main/resources/wsdl/CustomWebService2.wsdl")
public class CustomWebService
    extends Service
{

    private final static URL CUSTOMWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMWEBSERVICE_EXCEPTION;
    private final static QName CUSTOMWEBSERVICE_QNAME = new QName("http://cloud.mos.ru/customWebService2/", "CustomWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/zagvo/IdeaProjects/SOAPCall/src/main/resources/wsdl/CustomWebService2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMWEBSERVICE_WSDL_LOCATION = url;
        CUSTOMWEBSERVICE_EXCEPTION = e;
    }

    public CustomWebService() {
        super(__getWsdlLocation(), CUSTOMWEBSERVICE_QNAME);
    }

    public CustomWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMWEBSERVICE_QNAME, features);
    }

    public CustomWebService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMWEBSERVICE_QNAME);
    }

    public CustomWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMWEBSERVICE_QNAME, features);
    }

    public CustomWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomWebServiceImpl
     */
    @WebEndpoint(name = "AdaptersWebServicePort")
    public CustomWebServiceImpl getAdaptersWebServicePort() {
        return super.getPort(new QName("http://cloud.mos.ru/customWebService2/", "AdaptersWebServicePort"), CustomWebServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomWebServiceImpl
     */
    @WebEndpoint(name = "AdaptersWebServicePort")
    public CustomWebServiceImpl getAdaptersWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cloud.mos.ru/customWebService2/", "AdaptersWebServicePort"), CustomWebServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMWEBSERVICE_EXCEPTION!= null) {
            throw CUSTOMWEBSERVICE_EXCEPTION;
        }
        return CUSTOMWEBSERVICE_WSDL_LOCATION;
    }

}
